### ISSUE TITLE
Question: How to modify your json files for use on windows directly?

### ISSUE THREAD

**Issue by SebastianBehrens** [varp/karabiner-rdp#3]
Stumbled across your set of remaps on [here](https://ke-complex-modifications.pqrs.org/?q=mac%20osx%20rdp) and realised they don't work for Windows directly. I guess it has something to do with the bundle identifiers, making the remaps work only on certain applications — anyways.

I wanted you to ask how I could modify the json, such that the remaps work when either a) switching to bluetooth slot 1 (almost like an implied windows layout when switching to that bluetooth channel) or if that is not possible b) when switching to windows (with the switch on the side of the keychron).

Please excuse some stupidity and maybe some naivity for asking that and that here, considering its not an issue.

Feel free to just close it without any hard feelings, if this is definitely not the place to ask such not-really-issue things here.

**Comment by varp** [comment]
Hi.

I just get a little bit confused... As I know, at least knew, but Karabiner Elements is MacOS specific software. It doesn't support Windows in any way.

Anyway, there is the [documentation](https://karabiner-elements.pqrs.org/docs/) for Karabiner Elements
