### ISSUE TITLE
[Feature request] Cmd+` (tilda) to toggle between windows of the same type

### ISSUE THREAD

**Issue by rohankhanna** [varp/karabiner-rdp#4]

**Comment by varp** [comment]
Hi. I think Windows doesn't has corresponding functionality. But I may be wrong. Could please attach some links to the corresponding functionality in Windows systems?

**Comment by rohankhanna** [comment]
Hey Varp, I have been using popOS 22.04 and it uses windows rdp as a default remote connection protocol.

**Comment by varp** [comment]
Just to clarify, that I understand you right. Do you connect from MacOS host to popOS 22.04 which uses windows rdp protocol ?

**Comment by rohankhanna** [comment]
Yes. PopOS uses a built-in Microsoft RDP based remote connection protocol(don't know if I'm using the word right), and it uses Alt-` to switch between window instances of the same application.

**Comment by varp** [comment]
@rohankhanna  sorry for the late answer. I just revisiting my repos for a case of unclosed issues and conversations. Am I right, Alt+` is standard behaviour for Windows since from which version? Or it's not standard behaviour?

**Comment by varp** [comment]
Closing because of not get answer from reporter. Feel free to reopen.
