### ISSUE TITLE
[Feature Request] CMD+Shift+Left Arrow &  CMD+Shift+Right Arrow 

### ISSUE THREAD

**Issue by Nickcom4** [varp/karabiner-rdp#5]
Useful everyday for efficiently highlighting text. Please let me know how to make donation to you. Your RDP complex modifications are very useful. :-)

**Comment by varp** [comment]
Hi, I've implemented. Need a couple days for testing and release

**Comment by varp** [comment]
@Nickcom4 Feature tested and waiting the [PR](https://github.com/pqrs-org/KE-complex_modifications/pull/1342) to be merged. Meanwhile, you can install it manually from the repo
