### ISSUE TITLE
[Feature Request] Option+` leading to WIN+TAB behavior of app switching

### ISSUE THREAD

**Issue by Nickcom4** [varp/karabiner-rdp#6]
Useful for window switching within RDP session.

**Comment by varp** [comment]
I've not find solution for this, because of translation of ```` Option+` ```` leads to Mac OS default behaviour Cmd+Tab, because Karabiner doesn't differentiate  `left_commad`, `left_gui` for PC and Mac. Both works as Meta key - Cmd on MacOS, Win on Windows, which under the hood have on key code.
