### ISSUE TITLE
map `cmd+/` to `ctrl + /`

### ISSUE THREAD

**Issue by RealKai42** [varp/karabiner-rdp#7]
Thanks for your repo, it's unbelievably helpful！

maybe we can add a mapping from `cmd+/` to `ctrl+/`, which will be helpful when adding comments in code

**Comment by RealKai42** [comment]
and `cmd+opt+i` to `ctrl+shift+i`, which will be helpful when opening dev tools in the browser

**Comment by varp** [comment]
@RealKai42 OK. Will do on holidays. Sorry for a long answer

**Comment by varp** [comment]
Done.
