### ISSUE TITLE
Windows Clipboard history RDP shortcut cmd+shift+V ->  windows logo key + v

### ISSUE THREAD

**Issue by tdaroly** [varp/karabiner-rdp#9]
Is there any way you can also add an option for getting clipboard history in windows? I tried this config using `left_gui` and it did not work.

What i am trying to accomplish:
command + shift + V -> windows logo key + v
![image](https://github.com/user-attachments/assets/c50f87a5-6677-43f3-8a96-d835237d462e)
Karabiner config i tried:
```json
{
    "description": "Map Cmd+Shift+V to Windows+V (Clipboard History) globally.",
    "manipulators": [
        {
            "from": {
                "key_code": "v",
                "modifiers": {
                    "mandatory": ["command", "shift"]
                }
            },
            "to": [
                {
                    "key_code": "v",
                    "modifiers": ["left_gui"]
                }
            ],
            "type": "basic"
        }
    ]
}
```

**Comment by tdaroly** [comment]
Hey Vardan, would you please mind taking a look at this ? :) no rush pls, it would be nice if this was possible and would save me lots of time copying and pasting single entities.

**Comment by varp** [comment]
Okay, I've made a [PR](https://github.com/varp/karabiner-rdp/pull/10), but it should be tested. Could you give me a 
- which Windows version do you using
- Karabiner Version
- and RDP software which you use to connect to Windows machine

If I would be lucky, I will test it on coming weekend

**Comment by tdaroly** [comment]
@varp 

The remote desktop has Windows 11.
Karabiner-Elements-15.3.0
RDP software is called `Windows App`

Let me add your config and test

This is a sample config that works
```json
{
    "description": "Map Cmd+T to Windows Ctrl+T for opening new tabs.",
    "manipulators": [
        {
            "from": {
                "key_code": "t",
                "modifiers": { "mandatory": ["command"] }
            },
            "to": [
                {
                    "key_code": "t",
                    "modifiers": ["control"]
                }
            ],
            "type": "basic"
        }
    ]
}
```

**Comment by tdaroly** [comment]
I just tried testing with this config and NO conditions and it does NOT work :(

```json
{
    "description": "Mac OSX RDP: Windows Clipboard History: Cmd+Shift+V to Win+V",
    "manipulators": [
        {
            "from": {
                "key_code": "v",
                "modifiers": { "mandatory": ["command", "shift"] }
            },
            "to": [
                {
                    "key_code": "v",
                    "modifiers": ["left_gui"]
                }
            ],
            "type": "basic"
        }
    ]
}
```

**Comment by tdaroly** [comment]
I use a MacBook to RDP into a windows machine via an app called "Windows App" on the MacBook. 

For clipboard history I'm not sure why the config were both trying doesn't work :(

**Comment by varp** [comment]
That's sad because I don't know why concrete mapping doesn't has an effect

**Comment by varp** [comment]
Okay. I've figured out why the mapping is not working. The problem is that `left_gui` is alias for cmd and vice versa, thus, you translating cmd+shift+v to cmd+v. It is Pointless. 
If there is ability to change shortcut for Clipboard History on target Windows machine it will resolve the problem, because on system level cmd+v on macos used fo Paste.

@tdaroly fyi
